name: Install cargo binaries
description: Install cargo binaries using cargo-binstall
inputs:
  binstall:
    description: "Programs to install with binstall"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install cargo-binstall
      shell: bash
      run: >
        curl -L --proto '=https' --tlsv1.3 -sSf https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | sudo tar -xzv -C /usr/bin

    - name: Install cargo bins
      shell: bash
      run: >
        cargo-binstall --no-confirm --min-tls-version 1.3 ${{ inputs.binstall }}
